### ISSUE TITLE
TLS for LP-Hosted Installations

### ISSUE THREAD

**Issue by kitschpatrol** [local-projects/lp.squidex-cms#6]
Security-conscious clients will likely want their data behind TLS.

**Comment by olaafrossi** [comment]
@kitschpatrol will get an SSL cert from

**Comment by kitschpatrol** [comment]
@olaafrossi I'm sharing the login with a client tomorrow so would be great to have the 🔒.

**Comment by kitschpatrol** [comment]
Solved, thanks Tim and Olaaf.
